#!/bin/sh
# env
# echo "jj set ci -u=$PLUGIN_JENKINS_URL -l=$PLUGIN_JENKINS_USER -t=$PLUGIN_JENKINS_TOKEN"
echo "jj run -a DEPLOY=$PLUGIN_JENKINS_DEPLOY -a IMG_TAG=$PLUGIN_JENKINS_IMG_TAG -a GIT_TAG=$PLUGIN_JENKINS_GIT_TAG -a CONF_PATH=$PLUGIN_JENKINS_CONF_PATH -a BRANCH_NAME=$PLUGIN_JENKINS_BRANCH -a GIT_MSG=$PLUGIN_JENKINS_GIT_MSG $PLUGIN_JENKINS_JOB"
jj set ci -u=$PLUGIN_JENKINS_URL -l=$PLUGIN_JENKINS_USER -t=$PLUGIN_JENKINS_TOKEN && \
jj run -a DEPLOY=$PLUGIN_JENKINS_DEPLOY -a IMG_TAG=$PLUGIN_JENKINS_IMG_TAG -a GIT_TAG=$PLUGIN_JENKINS_GIT_TAG -a CONF_PATH=$PLUGIN_JENKINS_CONF_PATH -a BRANCH_NAME=$PLUGIN_JENKINS_BRANCH -a GIT_MSG="${PLUGIN_JENKINS_GIT_MSG}" $PLUGIN_JENKINS_JOB


